-- CLEAR
DELETE FROM TRANSACTIONS;

DELETE FROM WALLETS;

DELETE FROM USERS;


-- CREATE USERS
INSERT INTO USERS (FULL_NAME, DOCUMENT, EMAIL, PASSWORD, CREATED_AT) VALUES('João da Silva - USER', '12345678900', 'joaodasilva@email.com', '123456', NOW());

INSERT INTO USERS (FULL_NAME, DOCUMENT, EMAIL, PASSWORD, CREATED_AT) VALUES('Maria de Souza - LOJISTA', '12345678911', 'mariadesouza@email.com', '654321', NOW());


-- CREATE WALLETS FOR USERS
INSERT INTO WALLETS (TYPE, BALANCE, USER_ID, CREATED_AT) VALUES ( 1, 1000.00,  (SELECT ID FROM USERS WHERE DOCUMENT = '12345678900' LIMIT 1), NOW() );

INSERT INTO WALLETS (TYPE, BALANCE, USER_ID, CREATED_AT) VALUES ( 2, 1000.00,  (SELECT ID FROM USERS WHERE DOCUMENT = '12345678911' LIMIT 1), NOW());