version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: picpay_scratch_db
    environment:
      POSTGRES_USER: picpay_user
      POSTGRES_PASSWORD: picpay@TeSt1
      POSTGRES_DB: picpay_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: